/** Central map of the hand-picked Canva export filenames to keep spaces/casing out of components. */
export const IMG = {
  watermark: "/images/watermark.png",
  closeEnvelope: "/images/close envelope png.png",
  openEnvelope: "/images/open envelope png.png",
  envelopePage: "/images/envelope page.png",
  envelopeFlap: "/images/envelope UP.png",
  envelopeBg: "/images/Envelope BG.jpg",
  handsInvite: "/images/hands invite.png",
  scratchHands: "/images/Scratch IMAGE.png",
  pinkFlower: "/images/pink flower.png",
  blueFlower: "/images/blue flower.png",
  pinkTassel: "/images/PINK TESSELS.png",
  blueTassel: "/images/BLUE TESSELS.png",
  jhoomer: "/images/ELEMENT 1.png",
  haldiBg: "/images/haldi BG.png",
  haldiBowls: "/images/HALDI.png",
  sufiNightBg: "/images/sufi night background.png",
  sufiDancer: "/images/sufi.png",
  moon: "/images/moon.png",
  anandKarajBg: "/images/anand karaj BG.png",
  venue: "/images/venue.png",
  fountain: "/images/FOUNTAIN IMAGE.png",
  rsvpBg: "/images/background of rsvp.png",
  rings: "/images/RINGS.png",
  backShape: "/images/back shape.png",
  fan: "/images/fan.png",
  pillar: "/images/pillar.png",
  frontImage: "/images/front image.jpg",
  monogramM: "/images/omkar sign.png",
  flowerPot: "/images/flower pot (2).png",
  mainBg: "/images/wallpaper.jpeg",
} as const;
